### ISSUE TITLE
New category for analytical tools

### ISSUE THREAD

**Issue by kolya182** [apbendi/use-dai#26]
Found this website https://saistats.com/ and repo https://github.com/nanexcool/saistats should we have a new category ?

**Comment by apbendi** [comment]
Hi @kolya182! Thanks for calling attention to saistats. I love that site, as well as daistats.com! The purpose of this repos is supposed to be for places where you can *spend* or otherwise do something with your DAI, not just learn about it. So I don't think listing that site here is quite the right fit. Please let me know if you disagree! Closing for now, and thanks again :)
